//! Arranged authority/save fixtures. Real campaign controls are verified separately.
use super::*;
use crate::formal_runtime::entry_test_support::acknowledge_ready;
use crate::save_v6::SaveV6;
use crate::world_v3::Vec3;
fn fixture(scene_id:&str)->FormalRuntime{
    let root=std::env::temp_dir().join(format!("beacon-{}-{}",std::process::id(),std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()));
    let r=FormalRuntime::new_with_save_dir(root).unwrap();r.pause().unwrap();r.stop_owner.store(true,Ordering::SeqCst);r.owner_handle.lock().unwrap().take().unwrap().join().unwrap();crate::production_scene_bootstrap::install(&r).unwrap();install(&r,scene_id);
    {let mut s=r.state.lock().unwrap();s.route.current_world_id="grey_hive".into();s.route.progress.iter_mut().find(|p|p.world_id=="grey_hive").unwrap().visit_id=1;s.paused=false;}r
}
fn install(r:&FormalRuntime,scene:&str){let registry=r.scene_registry.lock().unwrap().clone().unwrap();r.install_scene_registry(registry,scene).unwrap();}
fn p(x:f32,z:f32)->Vec3{Vec3::new(x,0.,z).unwrap()}
fn position(r:&FormalRuntime,pos:Vec3){r.state.lock().unwrap().world.player.position_m=pos;}
fn saved(r:&FormalRuntime)->SaveV6{SaveV6::capture(&r.state.lock().unwrap(),r.scene_runtime.lock().unwrap().as_ref()).unwrap()}
fn fingerprint(r:&FormalRuntime)->String{let s=r.state.lock().unwrap();format!("{:?}",(&s.world,&s.world_persistent_v1,&s.route,&s.capabilities,&s.presentation_events,s.next_presentation_event_id,&*r.scene_runtime.lock().unwrap()))}
fn activate(r:&FormalRuntime,id:&str,request:&str)->FormalInteractionResponse{position(r,if id==MOUNT_ID{p(17.,8.)}else{p(8.,8.)});r.activate_scene_interaction(id,request,r.snapshot().unwrap().world_epoch).unwrap()}
fn progress(r:&FormalRuntime,event:&str){let mut s=r.state.lock().unwrap();let rev=s.world.revision;assert!(matches!(apply_route_command(&mut s.route,RouteCommand::Progress{event_id:event.into(),request_id:format!("historical-{event}")},rev),RouteResult::Applied{..}));}
fn prerequisites(r:&FormalRuntime){progress(r,"hive_power");progress(r,"hive_lockdown");}
fn finish_old(r:&FormalRuntime){progress(r,EXTRACT_EVENT);let mut s=r.state.lock().unwrap();let rev=s.world.revision;assert!(matches!(apply_route_command(&mut s.route,RouteCommand::Complete{world_id:"grey_hive".into(),request_id:"historical-complete".into()},rev),RouteResult::Applied{..}));}
#[test]
fn native_new_initializes_uncollected_but_generic_new_and_legacy_absence_remain_distinct(){
    let r=fixture("gh_beacon");assert!(saved(&r).world_persistent_v1.grey_hive.beacon.is_none());let before=r.snapshot().unwrap();assert_eq!(before.grey_hive_beacon.unwrap().state,Stage::Uncollected);let next=r.reset_new().unwrap();assert!(next.entry_token.is_some());assert_eq!(saved(&r).world_persistent_v1.grey_hive.beacon,Some(GreyHiveBeaconState::new_uncollected()));assert!(next.grey_hive_beacon.is_none());acknowledge_ready(&r,next);
    let generic=FormalRuntime::new_with_save_dir(std::env::temp_dir().join(format!("beacon-generic-{}",std::process::id()))).unwrap();generic.pause().unwrap();generic.stop_owner.store(true,Ordering::SeqCst);generic.owner_handle.lock().unwrap().take().unwrap().join().unwrap();generic.reset_new().unwrap();assert!(generic.state.lock().unwrap().world_persistent_v1.grey_hive.beacon.is_none());
}
#[test]
fn collect_then_optional_mount_is_atomic_idempotent_and_creates_no_route_or_capability_reward(){
    let r=fixture("gh_beacon");let base=saved(&r);let view=r.snapshot().unwrap();assert!(view.interactables.iter().find(|i|i.entity_id==COLLECT_ID).unwrap().active);assert!(!view.interactables.iter().find(|i|i.entity_id==MOUNT_ID).unwrap().active);
    let missing=activate(&r,MOUNT_ID,"mount-retry");assert_eq!(missing.error_code.as_deref(),Some("E_BEACON_NOT_CARRIED"));assert!(saved(&r).world_persistent_v1.grey_hive.beacon.is_none());
    let collected=activate(&r,COLLECT_ID,"collect-once");assert!(collected.applied);assert_eq!(collected.view.grey_hive_beacon.unwrap().state,Stage::Carried);let carried=saved(&r);assert_eq!(carried.save.progression,base.save.progression);assert_eq!(carried.save.capabilities,base.save.capabilities);assert_eq!(carried.save.inventory,base.save.inventory);assert_eq!(carried.save.player.current_hp,base.save.player.current_hp);
    position(&r,p(8.,8.));let before=fingerprint(&r);let repeat=activate(&r,COLLECT_ID,"collect-once");assert!(!repeat.applied&&repeat.already_applied);assert_eq!(fingerprint(&r),before);
    let collision=activate(&r,MOUNT_ID,"collect-once");assert_eq!(collision.error_code.as_deref(),Some("E_BEACON_REQUEST_COLLISION"));let mounted=activate(&r,MOUNT_ID,"mount-retry");assert!(mounted.applied);assert_eq!(mounted.view.grey_hive_beacon.unwrap().state,Stage::Mounted);let record=saved(&r).world_persistent_v1.grey_hive.beacon.unwrap();assert_eq!(record.receipts.iter().map(|r|r.action).collect::<Vec<_>>(),[Action::Collect,Action::Mount]);assert_eq!(record.receipts[1].request_id,"mount-retry");
    let before=fingerprint(&r);assert!(activate(&r,MOUNT_ID,"mount-retry").already_applied);assert_eq!(fingerprint(&r),before);let s=r.state.lock().unwrap();assert_eq!(s.presentation_events.iter().filter(|e|e.kind=="GreyHiveBeaconCollected").count(),1);assert_eq!(s.presentation_events.iter().filter(|e|e.kind=="GreyHiveBeaconMounted").count(),1);
}
#[test]
fn source_epoch_range_nonfinite_pause_dead_and_request_collisions_never_claim_or_mutate(){
    for fault in ["stale","scene-epoch","far","height","nan","route","pause","dead","request"]{let r=fixture("gh_beacon");position(&r,p(8.,8.));let epoch=r.snapshot().unwrap().world_epoch;
        {let mut s=r.state.lock().unwrap();match fault{"far"=>s.world.player.position_m=p(1.,1.),"height"=>s.world.player.position_m.y_m=3.,"nan"=>s.world.player.position_m.x_m=f32::NAN,"route"=>s.route.current_world_id="mist_harbor".into(),"pause"=>s.paused=true,"dead"=>s.world.player_hp=0,_=>{}}}
        if fault=="scene-epoch"{r.scene_runtime.lock().unwrap().as_mut().unwrap().world_epoch+=1;}
        if fault=="request"{r.scene_runtime.lock().unwrap().as_mut().unwrap().claim_command_request("retry",epoch).unwrap();}
        let before=fingerprint(&r);let result=r.activate_scene_interaction(COLLECT_ID,"retry",epoch+u64::from(fault=="stale"));assert!(result.is_err()||!result.unwrap().applied,"{fault}");assert_eq!(fingerprint(&r),before,"{fault}");
        if fault=="far"{position(&r,p(8.,8.));assert!(r.activate_scene_interaction(COLLECT_ID,"retry",epoch).unwrap().applied);}
    }
    let r=fixture("gh_exit");let before=fingerprint(&r);assert_eq!(r.interact(COLLECT_ID,"old-no-epoch").unwrap_err(),"E_INTERACTION_SOURCE_EPOCH_REQUIRED");assert_eq!(r.interact(EXTRACT_ID,"old-extract").unwrap_err(),"E_INTERACTION_SOURCE_EPOCH_REQUIRED");assert_eq!(fingerprint(&r),before);
}
#[test]
fn late_revision_failure_rolls_back_both_owners_and_allows_same_request_retry(){
    let r=fixture("gh_beacon");position(&r,p(8.,8.));let normal=r.state.lock().unwrap().world.revision.authority_revision;r.state.lock().unwrap().world.revision.authority_revision=u64::MAX;let before=fingerprint(&r);let response=r.activate_scene_interaction(COLLECT_ID,"overflow-retry",r.snapshot().unwrap().world_epoch).unwrap();assert!(!response.applied);assert!(response.error_code.unwrap().starts_with("E_WORLD_REVISION"));assert_eq!(fingerprint(&r),before);r.state.lock().unwrap().world.revision.authority_revision=normal;assert!(activate(&r,COLLECT_ID,"overflow-retry").applied);
}
#[test]
fn old_static_activations_and_saved_route_ledger_survive_continue_without_manufacturing_receipts(){
    let r=fixture("gh_beacon");let epoch=r.snapshot().unwrap().world_epoch;{let mut scene=r.scene_runtime.lock().unwrap();let scene=scene.as_mut().unwrap();scene.interact(COLLECT_ID,"old-collect-marker",epoch,p(8.,8.)).unwrap();scene.interact(MOUNT_ID,"old-mount-marker",epoch,p(17.,8.)).unwrap();}
    assert!(!activate(&r,COLLECT_ID,"old-collect-marker").applied,"same live epoch retains the existing request claim");
    prerequisites(&r);let old=saved(&r);assert!(old.world_persistent_v1.grey_hive.beacon.is_none());r.save().unwrap();r.save_slot("old","Old",true).unwrap();let path=crate::save_v6::save_path(&r.save_root);let slot=r.save_root.join("slots/old/slot-v6.json");let bytes=std::fs::read(&path).unwrap();let slot_bytes=std::fs::read(&slot).unwrap();
    for from_slot in [false,true]{let prepared=if from_slot{r.continue_slot("old").unwrap()}else{r.continue_saved().unwrap()};assert!(r.state.lock().unwrap().paused&&prepared.entry_token.is_some());assert!(saved(&r).world_persistent_v1.grey_hive.beacon.is_none());assert!(r.scene_runtime.lock().unwrap().as_ref().unwrap().object_activated(COLLECT_ID));assert!(r.scene_runtime.lock().unwrap().as_ref().unwrap().object_activated(MOUNT_ID));acknowledge_ready(&r,prepared);position(&r,p(8.,8.));assert!(!r.activate_scene_interaction(COLLECT_ID,"old-collect-marker",epoch).unwrap().applied,"old source epoch never rebinds");assert_eq!(saved(&r).save.scene_states,old.save.scene_states);assert_eq!(serde_json::to_value(&saved(&r).save.progression).unwrap()["processedRequestIds"],serde_json::to_value(&old.save.progression).unwrap()["processedRequestIds"]);assert!(saved(&r).world_persistent_v1.grey_hive.beacon.is_none());assert!(activate(&r,COLLECT_ID,"physical-reconfirm").applied);assert_eq!(saved(&r).save.progression,old.save.progression);assert_eq!(std::fs::read(&path).unwrap(),bytes);assert_eq!(std::fs::read(&slot).unwrap(),slot_bytes);}
}
#[test]
fn carried_and_mounted_records_roundtrip_but_malformed_current_file_and_slot_are_atomic(){
    for mount in [false,true]{let r=fixture("gh_beacon");assert!(activate(&r,COLLECT_ID,"collect").applied);if mount{assert!(activate(&r,MOUNT_ID,"mount").applied);}let current=saved(&r);r.save().unwrap();r.save_slot("current","Current",true).unwrap();let path=crate::save_v6::save_path(&r.save_root);let slot=r.save_root.join("slots/current/slot-v6.json");let bytes=std::fs::read(&path).unwrap();let slot_bytes=std::fs::read(&slot).unwrap();
        for from_slot in [false,true]{let view=if from_slot{r.continue_slot("current").unwrap()}else{r.continue_saved().unwrap()};assert_eq!(saved(&r).world_persistent_v1.grey_hive.beacon,current.world_persistent_v1.grey_hive.beacon);assert!(r.presentation_events_since(view.world_epoch,0).unwrap().is_empty());acknowledge_ready(&r,view);assert_eq!(std::fs::read(&path).unwrap(),bytes);assert_eq!(std::fs::read(&slot).unwrap(),slot_bytes);}
        for fault in ["version","count","order","duplicate","future","zero","request","state","null","missing-inner"]{let mut raw=serde_json::to_value(&current).unwrap();let b=&mut raw["worldPersistentV1"]["greyHive"]["beacon"];match fault{"version"=>b["schemaVersion"]=serde_json::json!(2),"count"=>b["receipts"]=serde_json::json!([]),"order"=>b["receipts"][0]["action"]=serde_json::json!("mount"),"duplicate"=>{let row=b["receipts"][0].clone();b["state"]=serde_json::json!("mounted");b["receipts"]=serde_json::json!([row.clone(),{"action":"mount","requestId":row["requestId"],"worldEpoch":row["worldEpoch"]}]);},"future"=>b["receipts"][0]["worldEpoch"]=serde_json::json!(current.save.revision.world_epoch+1),"zero"=>b["receipts"][0]["worldEpoch"]=serde_json::json!(0),"request"=>b["receipts"][0]["requestId"]=serde_json::json!("bad request"),"state"=>b["state"]=serde_json::json!("uncollected"),"null"=>*b=serde_json::Value::Null,_=>{b.as_object_mut().unwrap().remove("receipts");}}
            if let Ok(bad)=serde_json::from_value::<SaveV6>(raw.clone()){assert!(crate::save_v6::write_save(&r.save_root,&bad).is_err(),"{fault}");assert!(crate::save_slots::overwrite_slot_v6(&r.save_root,"current","Bad",&bad).is_err());assert_eq!(std::fs::read(&path).unwrap(),bytes);assert_eq!(std::fs::read(&slot).unwrap(),slot_bytes);}
            let bad_bytes=serde_json::to_vec(&raw).unwrap();std::fs::write(&path,&bad_bytes).unwrap();let mut wrapper:serde_json::Value=serde_json::from_slice(&slot_bytes).unwrap();wrapper["save"]=raw;let bad_slot=serde_json::to_vec(&wrapper).unwrap();std::fs::write(&slot,&bad_slot).unwrap();let before=fingerprint(&r);assert!(r.continue_saved().is_err(),"{fault}");assert!(r.continue_slot("current").is_err());assert_eq!(fingerprint(&r),before);assert_eq!(std::fs::read(&path).unwrap(),bad_bytes);assert_eq!(std::fs::read(&slot).unwrap(),bad_slot);std::fs::write(&path,&bytes).unwrap();std::fs::write(&slot,&slot_bytes).unwrap();}
    }
}
#[test]
fn legacy_completed_gh_stays_completed_without_beacon_and_current_uncollected_cannot_claim_completion(){
    let r=fixture("gh_exit");prerequisites(&r);finish_old(&r);let old=saved(&r);assert!(old.world_persistent_v1.grey_hive.beacon.is_none());r.save().unwrap();let path=crate::save_v6::save_path(&r.save_root);let bytes=std::fs::read(&path).unwrap();let view=r.continue_saved().unwrap();assert!(view.grey_hive_beacon.as_ref().unwrap().legacy_completed_without_receipt);assert_eq!(view.grey_hive_beacon.as_ref().unwrap().state,Stage::Uncollected);assert_eq!(saved(&r).save.progression,old.save.progression);assert!(saved(&r).world_persistent_v1.grey_hive.beacon.is_none());acknowledge_ready(&r,view);assert_eq!(std::fs::read(&path).unwrap(),bytes);
    position(&r,p(8.,8.));let returned=r.use_world_gate("gh_extraction_return_to_rs","legacy-return",r.snapshot().unwrap().world_epoch).unwrap();assert_eq!(returned.world_id,"return_station");assert!(returned.entry_token.is_some());acknowledge_ready(&r,returned);assert!(saved(&r).world_persistent_v1.grey_hive.beacon.is_none());assert!(completed(&r.state.lock().unwrap().route));assert_eq!(std::fs::read(&path).unwrap(),bytes);
    let mut bad=old;bad.world_persistent_v1.grey_hive.beacon=Some(GreyHiveBeaconState::new_uncollected());assert!(bad.validate().is_err());assert!(crate::save_v6::write_save(&r.save_root,&bad).is_err());assert_eq!(std::fs::read(&path).unwrap(),bytes);
}
#[test]
fn strict_native_gh_generic_progress_complete_enter_revisit_are_blocked_while_generic_fixture_retains_semantics(){
    let r=fixture("gh_beacon");for request in [RouteCommandRequest::Progress{event_id:"hive_power".into(),request_id:"bypass-power".into()},RouteCommandRequest::Progress{event_id:EXTRACT_EVENT.into(),request_id:"bypass-extract".into()},RouteCommandRequest::Enter{world_id:"grey_hive".into(),request_id:"bypass-enter".into()},RouteCommandRequest::Complete{world_id:"grey_hive".into(),request_id:"bypass-complete".into()},RouteCommandRequest::Revisit{world_id:"grey_hive".into(),request_id:"bypass-revisit".into()}]{let before=fingerprint(&r);assert_eq!(r.apply_route_command(request).unwrap_err(),"E_GREY_HIVE_AUTHORED_COMMAND_REQUIRED");assert_eq!(fingerprint(&r),before);}
    let generic=FormalRuntime::new_with_save_dir(std::env::temp_dir().join(format!("beacon-route-generic-{}",std::process::id()))).unwrap();generic.pause().unwrap();generic.stop_owner.store(true,Ordering::SeqCst);generic.owner_handle.lock().unwrap().take().unwrap().join().unwrap();generic.state.lock().unwrap().paused=false;assert!(generic.apply_route_command(RouteCommandRequest::Progress{event_id:"hive_power".into(),request_id:"generic-power".into()}).unwrap().applied);assert!(generic.state.lock().unwrap().world_persistent_v1.grey_hive.beacon.is_none());
}
#[test]
fn old_incomplete_exit_has_real_backtrack_collect_and_exact_console_completion_even_with_old_event(){
    for old_event in [false,true]{let r=fixture("gh_exit");prerequisites(&r);if old_event{progress(&r,EXTRACT_EVENT);let epoch=r.snapshot().unwrap().world_epoch;r.scene_runtime.lock().unwrap().as_mut().unwrap().interact(EXTRACT_ID,"old-exit-marker",epoch,p(8.,8.)).unwrap();}
        r.save().unwrap();let path=crate::save_v6::save_path(&r.save_root);let bytes=std::fs::read(&path).unwrap();let old_epoch=r.snapshot().unwrap().world_epoch;acknowledge_ready(&r,r.continue_saved().unwrap());position(&r,p(8.,8.));let epoch=r.snapshot().unwrap().world_epoch;let before=fingerprint(&r);assert_eq!(r.interact(EXTRACT_ID,"no-epoch-extract").unwrap_err(),"E_INTERACTION_SOURCE_EPOCH_REQUIRED");assert!(!r.activate_scene_interaction(EXTRACT_ID,"late-extract",old_epoch).unwrap().applied);assert_eq!(fingerprint(&r),before);let denied=activate(&r,EXTRACT_ID,"finish-retry");assert_eq!(denied.error_code.as_deref(),Some("E_BEACON_REQUIRED"));assert_eq!(fingerprint(&r),before);
        position(&r,p(1.5,8.));let back=r.transition_scene("gh_exit_to_beacon","back-to-beacon",epoch).unwrap();acknowledge_ready(&r,back);assert_eq!(r.snapshot().unwrap().scene_id,"gh_beacon");assert!(activate(&r,COLLECT_ID,"physical-collect").applied);position(&r,p(22.5,8.));let forward=r.transition_scene("gh_beacon_to_exit","back-to-exit",r.snapshot().unwrap().world_epoch).unwrap();acknowledge_ready(&r,forward);let extracted=activate(&r,EXTRACT_ID,"finish-retry");assert!(extracted.applied,"{:?}",extracted.error_code);assert!(completed(&r.state.lock().unwrap().route));assert!(owned(&r.state.lock().unwrap()));assert_eq!(std::fs::read(&path).unwrap(),bytes);
    }
}
#[test]
fn forged_trigger_mixed_receipt_and_complete_request_collision_roll_back_extraction(){
    let r=fixture("gh_beacon");assert!(activate(&r,COLLECT_ID,"collect").applied);install(&r,"gh_exit");r.state.lock().unwrap().paused=false;prerequisites(&r);position(&r,p(8.,8.));let scene=r.scene_runtime.lock().unwrap().clone().unwrap();let before=fingerprint(&r);
    for events in [vec![SceneEvent::Trigger{id:"fake-trigger".into(),event_id:EXTRACT_EVENT.into()}],vec![SceneEvent::Interaction{id:"fake-console".into(),event_id:Some(EXTRACT_EVENT.into())}],vec![SceneEvent::Interaction{id:EXTRACT_ID.into(),event_id:Some(EXTRACT_EVENT.into())},SceneEvent::Trigger{id:"extra".into(),event_id:EXTRACT_EVENT.into()}]]{let mut s=r.state.lock().unwrap().clone();assert!(apply_scene_progress(&mut s,&scene,&events,"forged").is_err());assert_eq!(fingerprint(&r),before);}
    {let mut s=r.state.lock().unwrap();let revision=s.world.revision;assert!(matches!(apply_route_command(&mut s.route,RouteCommand::Progress{event_id:"hive_power".into(),request_id:"scene-complete-collision".into()},revision),RouteResult::Applied{..}));}
    // A valid already-owned event is used only to arrange a global request-ID collision.
    assert!(serde_json::to_value(&r.state.lock().unwrap().route).unwrap()["processedRequestIds"].as_array().unwrap().iter().any(|id|id.as_str()==Some("scene-complete-collision")));
    let before=fingerprint(&r);let result=activate(&r,EXTRACT_ID,"collision");assert!(!result.applied);assert!(result.error_code.as_ref().is_some_and(|e|e.contains("DUPLICATE")));assert_eq!(fingerprint(&r),before);
}
