//! Arranged historical-save and public receipt tests, not campaign proof.
use super::*;
use crate::formal_runtime::entry_test_support::acknowledge_ready;
use crate::save_v6::SaveV6;
use crate::world_v3::{ActorAttackKind,ActorRuntimeEvent};
fn fixture(scene:&str)->FormalRuntime{
    let root=std::env::temp_dir().join(format!("signal-roster-{}-{}",std::process::id(),std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()));
    let r=FormalRuntime::new_with_save_dir(root).unwrap();r.pause().unwrap();r.stop_owner.store(true,Ordering::SeqCst);r.owner_handle.lock().unwrap().take().unwrap().join().unwrap();crate::production_scene_bootstrap::install(&r).unwrap();let registry=r.scene_registry.lock().unwrap().clone().unwrap();r.install_scene_registry(registry,scene).unwrap();
    {let mut s=r.state.lock().unwrap();s.route.current_world_id="mist_harbor".into();s.route.progress.iter_mut().find(|p|p.world_id=="mist_harbor").unwrap().visit_id=1;}r
}
fn capture(r:&FormalRuntime)->SaveV6{SaveV6::capture(&r.state.lock().unwrap(),r.scene_runtime.lock().unwrap().as_ref()).unwrap()}
fn rows(r:&FormalRuntime)->Vec<ActorRuntime>{r.state.lock().unwrap().world.generic_actors.clone()}
fn old_row(a:&ActorRuntime,phase:&str)->ActorRuntime{
    let mut old=ActorRuntime::spawn(&a.entity_id,WRAITH,a.home_m).unwrap();old.position_m=a.position_m;old.hp=if phase=="dead"{0}else{31};old.attack_serial=7;
    old.state=if phase=="dead"{ActorAiState::Dead}else if phase=="windup"{ActorAiState::Windup}else{ActorAiState::Cooldown};old.state_remaining_ms=if phase=="dead"{0}else{1};
    if phase=="windup"{old.current_attack=Some(ActorAttackKind::HeavyMelee);old.windup_origin_m=Some(old.position_m);}assert!(old.validate());old
}
#[test]
fn exact_ten_existing_wraiths_are_admitted_without_new_rosters_or_warden_alias(){
    let mut count=0;for scene in SCENES{let r=fixture(scene);let save=capture(&r);assert_eq!(save.world_persistent_v1.mist_harbor.signal_wraith_controller_version,1);let expected=authored(&canonical(scene).unwrap()).unwrap();assert!(exact(&save.save.generic_actors,&expected));
        for a in save.save.generic_actors.iter().filter(|a|a.entity_type==WRAITH){count+=1;assert_eq!(a.controller_variant,1);assert_eq!(a.hp,45);let view=r.snapshot().unwrap();let row=view.actors.iter().find(|v|v.entity_id==a.entity_id).unwrap();assert_eq!(row.entity_type,WRAITH);assert!(row.signal_perception.is_some());assert!(!serde_json::to_string(row).unwrap().contains("Hp"));}}
    assert_eq!(count,10);let r=fixture("mh_warden_arena");let save=capture(&r);assert_eq!(save.world_persistent_v1.mist_harbor.signal_wraith_controller_version,0);assert_eq!(save.save.generic_actors[0].controller_variant,0);assert!(r.snapshot().unwrap().actors.iter().all(|a|a.signal_perception.is_none()));
}
#[test]
fn old_all_legacy_empty_and_current_rows_upgrade_atomically_without_save_rewrite(){
    for scene in SCENES{for phase in ["windup","cooldown","dead","empty","current"]{let r=fixture(scene);let mut old=capture(&r);old.world_persistent_v1.mist_harbor.signal_wraith_controller_version=0;old.world_persistent_v1.mark_explored("mh_dq_flooded_channel").unwrap();old.world_persistent_v1.mist_harbor.pump.start("mist_harbor",true,0).unwrap();old.world_persistent_v1.resolve_at(6000).unwrap();
        if phase=="empty"{old.save.generic_actors.clear();old.world_persistent_v1.mist_harbor.tidebound_actor_roster_version=0;}else if phase!="current"{for a in &mut old.save.generic_actors{if a.entity_type==WRAITH{*a=old_row(a,phase);}}}
        crate::save_v6::write_save(&r.save_root,&old).unwrap();crate::save_slots::create_slot_v6(&r.save_root,"old","Old",&old).unwrap();let path=crate::save_v6::save_path(&r.save_root);let slot=r.save_root.join("slots/old/slot-v6.json");let bytes=std::fs::read(&path).unwrap();let slot_bytes=std::fs::read(&slot).unwrap();let mut epoch=r.snapshot().unwrap().world_epoch;
        for is_slot in [false,false,true]{let view=if is_slot{r.continue_slot("old").unwrap()}else{r.continue_saved().unwrap()};assert!(view.entry_token.is_some()&&r.state.lock().unwrap().paused);assert!(view.world_epoch>epoch);epoch=view.world_epoch;let now=capture(&r);assert_eq!(now.world_persistent_v1.mist_harbor.signal_wraith_controller_version,1);assert_eq!(now.world_persistent_v1.mist_harbor.pump,old.world_persistent_v1.mist_harbor.pump);assert_eq!(now.world_persistent_v1.mist_harbor.explored_region_ids,old.world_persistent_v1.mist_harbor.explored_region_ids);assert_eq!(now.save.progression,old.save.progression);
            for prior in &old.save.generic_actors{let a=now.save.generic_actors.iter().find(|a|a.entity_id==prior.entity_id).unwrap();assert!(identity(a,prior));assert_eq!((a.hp,a.position_m,a.attack_serial),(prior.hp,prior.position_m,prior.attack_serial));if prior.entity_type==WRAITH&&prior.controller_variant==0{assert_eq!(a.state,if a.hp==0{ActorAiState::Dead}else{ActorAiState::Idle});assert_eq!(a.current_attack,None);assert_eq!(a.state_remaining_ms,0);}else{assert_eq!(a,prior);}}
            assert!(!r.presentation_events_since(view.world_epoch,0).unwrap().iter().any(|e|e.kind=="EnemyDeath"||e.attack_kind.as_deref()==Some("signal_shot")));acknowledge_ready(&r,view);assert_eq!(std::fs::read(&path).unwrap(),bytes);assert_eq!(std::fs::read(&slot).unwrap(),slot_bytes);}
    }}
}
#[test]
fn malformed_mixed_and_current_missing_controller_rows_reject_write_and_continue(){
    for fault in ["legacy-current-marker","mixed-legacy-marker","missing","empty","extra","duplicate","type","home","controller","phase","version"]{let r=fixture("mh_signal_yard");r.save().unwrap();r.save_slot("safe","Safe",true).unwrap();let path=crate::save_v6::save_path(&r.save_root);let slot_path=r.save_root.join("slots/safe/slot-v6.json");let bytes=std::fs::read(&path).unwrap();let slot_bytes=std::fs::read(&slot_path).unwrap();let mut bad=capture(&r);
        match fault{"legacy-current-marker"=>{for a in &mut bad.save.generic_actors{*a=old_row(a,"windup");}},"mixed-legacy-marker"=>{bad.world_persistent_v1.mist_harbor.signal_wraith_controller_version=0;bad.save.generic_actors[0]=old_row(&bad.save.generic_actors[0],"windup");},"missing"=>{bad.save.generic_actors.pop();},"empty"=>bad.save.generic_actors.clear(),"extra"=>{let mut a=bad.save.generic_actors[0].clone();a.entity_id.push_str("x");bad.save.generic_actors.push(a);},"duplicate"=>bad.save.generic_actors[1]=bad.save.generic_actors[0].clone(),"type"=>bad.save.generic_actors[0].entity_type="enemy.mist_harbor.drowned".into(),"home"=>bad.save.generic_actors[0].home_m.x_m+=0.1,"controller"=>bad.save.generic_actors[0].ordinary=None,"phase"=>bad.save.generic_actors[0].state_remaining_ms=1,"version"=>bad.world_persistent_v1.mist_harbor.signal_wraith_controller_version=2,_=>unreachable!()}
        assert!(crate::save_v6::write_save(&r.save_root,&bad).is_err(),"{fault}");assert!(crate::save_slots::overwrite_slot_v6(&r.save_root,"safe","Bad",&bad).is_err());assert_eq!(std::fs::read(&path).unwrap(),bytes);assert_eq!(std::fs::read(&slot_path).unwrap(),slot_bytes);let raw=serde_json::to_vec(&bad).unwrap();std::fs::write(&path,&raw).unwrap();let mut slot:serde_json::Value=serde_json::from_slice(&slot_bytes).unwrap();slot["save"]=serde_json::to_value(&bad).unwrap();let raw_slot=serde_json::to_vec(&slot).unwrap();std::fs::write(&slot_path,&raw_slot).unwrap();let before=r.snapshot().unwrap();let actors=rows(&r);assert!(r.continue_saved().is_err(),"{fault}");assert!(r.continue_slot("safe").is_err());assert_eq!(r.snapshot().unwrap(),before);assert_eq!(rows(&r),actors);assert_eq!(std::fs::read(&path).unwrap(),raw);assert_eq!(std::fs::read(&slot_path).unwrap(),raw_slot);
    }
}
fn phase(r:&FormalRuntime,active:bool)->ActorRuntime{let mut s=r.state.lock().unwrap();let kcc=s.kcc.clone();let a=s.world.generic_actors.iter_mut().find(|a|a.entity_type==WRAITH).unwrap();let target=Vec3{x_m:a.position_m.x_m+3.,..a.position_m};for _ in 0..180{if a.state==if active{ActorAiState::Active}else{ActorAiState::Windup}{break;}a.tick(target,&kcc,1./60.,false);}assert_eq!(a.current_attack,Some(ActorAttackKind::SignalShot));if !active{a.state_remaining_ms=1;}assert!(a.validate());a.clone()}
#[test]
fn saved_one_tick_cast_and_zero_elapsed_shot_publish_precise_cues_while_held(){
    for active in [false,true]{let r=fixture("mh_signal_yard");let expected=phase(&r,active);r.save().unwrap();let view=r.continue_saved().unwrap();assert!(view.entry_token.is_some()&&r.state.lock().unwrap().paused);assert_eq!(rows(&r)[0],expected);let row=view.actors.iter().find(|a|a.entity_id==expected.entity_id).unwrap();assert_eq!(row.signal_perception.as_ref().unwrap().positions_m,vec![expected.position_m]);assert!(row.signal_perception.as_ref().unwrap().precise);assert_eq!(row.transform.position_m,expected.position_m);
        let cues=r.presentation_events_since(view.world_epoch,0).unwrap();let cue=cues.iter().find(|e|e.actor_id.as_deref()==Some(&expected.entity_id)&&e.attack_kind.as_deref()==Some("signal_shot")).unwrap();assert_eq!(cue.kind,if active{"SignalShotMotion"}else{"EnemyAttackTelegraph"});assert_eq!(cue.position_m,expected.position_m);assert_eq!(cue.direction_rad,std::f32::consts::FRAC_PI_2);assert_eq!(cue.radius_m,0.18);assert_eq!(cue.range_m,Some(8.));assert!(cue.duration_ms.unwrap()>0);acknowledge_ready(&r,view);assert_eq!(rows(&r)[0],expected);
        let context=r.snapshot().unwrap();r.pause_context_ordered(&SessionContext {world_id:context.world_id.clone(),scene_id:context.scene_id.clone(),world_epoch:context.world_epoch},1).unwrap();let before=rows(&r);let refreshed=r.pause_context_ordered(&SessionContext {world_id:context.world_id.clone(),scene_id:context.scene_id.clone(),world_epoch:context.world_epoch},2).unwrap();assert_eq!(rows(&r),before);assert!(refreshed.actors.iter().find(|a|a.entity_id==expected.entity_id).unwrap().signal_perception.as_ref().unwrap().precise);
    }
}
#[test]
fn public_ambiguity_is_stable_bounded_and_mapping_or_threat_reveals_without_hp_or_input_change(){
    let r=fixture("mh_signal_yard");{let mut s=r.state.lock().unwrap();s.world.player.position_m=Vec3::new(11.,0.,6.).unwrap();}let before=capture(&r);let first=r.snapshot().unwrap();let a=first.actors.iter().find(|a|a.entity_id=="mh_signal_yard_signal_wraith_01").unwrap();let projection=a.signal_perception.as_ref().unwrap();assert!(!projection.precise);assert_eq!(projection.positions_m.len(),2);assert_eq!(a.transform.position_m,signal_wraith_presentation::anchor(projection));assert_ne!(a.transform.position_m,rows(&r)[0].position_m);for _ in 0..10{assert_eq!(r.snapshot().unwrap(),first);}assert_eq!(capture(&r),before);
    {r.state.lock().unwrap().effective_rules_v6.capability_permissions.insert(CapabilityPermission::AcousticMapping);}let mapped=r.snapshot().unwrap();let row=mapped.actors.iter().find(|row|row.entity_id==a.entity_id).unwrap();assert!(row.signal_perception.as_ref().unwrap().precise);assert_eq!(row.transform.position_m,rows(&r)[0].position_m);assert_eq!(capture(&r).save.generic_actors,before.save.generic_actors);r.state.lock().unwrap().effective_rules_v6.capability_permissions.remove(&CapabilityPermission::AcousticMapping);
    phase(&r,false);let view=r.snapshot().unwrap();assert!(view.actors.iter().find(|a|a.entity_id=="mh_signal_yard_signal_wraith_01").unwrap().signal_perception.as_ref().unwrap().precise);
}
#[test]
fn late_entry_failure_rolls_back_migration_and_old_file_then_retries_normally(){
    let source=fixture("mh_signal_yard");let mut old=capture(&source);old.world_persistent_v1.mist_harbor.signal_wraith_controller_version=0;for a in &mut old.save.generic_actors{*a=old_row(a,"windup");}let r=fixture("mh_fog_pier");crate::save_v6::write_save(&r.save_root,&old).unwrap();let path=crate::save_v6::save_path(&r.save_root);let bytes=std::fs::read(&path).unwrap();r.state.lock().unwrap().entry_generation=build_ui::MAX_SAFE_REVISION;let before=capture(&r);assert_eq!(r.continue_saved().unwrap_err(),"E_SCENE_ENTRY_GENERATION_EXHAUSTED");assert_eq!(capture(&r),before);assert_eq!(std::fs::read(&path).unwrap(),bytes);r.state.lock().unwrap().entry_generation=0;acknowledge_ready(&r,r.continue_saved().unwrap());assert_eq!(capture(&r).world_persistent_v1.mist_harbor.signal_wraith_controller_version,1);assert_eq!(std::fs::read(&path).unwrap(),bytes);
}

#[test]
fn signal_terminal_receipts_and_relocation_keep_captured_geometry_and_reject_false_cues(){
    let r=fixture("mh_signal_yard");phase(&r,true);let scene=r.scene_runtime.lock().unwrap().clone().unwrap();let mut s=r.state.lock().unwrap();let kcc=s.kcc.clone();let target=Vec3::new(13.,0.,6.).unwrap();let mut terminal=vec![];
    while s.world.generic_actors[0].state==ActorAiState::Active{let out=s.world.generic_actors[0].tick(target,&kcc,1./60.,false);if out.damage_to_player.is_some(){terminal=out.events;}}
    assert!(!terminal.is_empty());ordinary_enemy_presentation::present_events(&mut s,Some(&scene),&terminal);let cue=s.presentation_events.last().unwrap();assert_eq!(cue.kind,"EnemyAttackImpact");assert_eq!(cue.direction_rad,std::f32::consts::FRAC_PI_2);assert_eq!(cue.range_m,Some(8.));assert_eq!(cue.attack_kind.as_deref(),Some("signal_shot"));
    let mut relocation=None;while s.world.generic_actors[0].state==ActorAiState::Cooldown{let out=s.world.generic_actors[0].tick(Vec3::new(11.,0.,6.).unwrap(),&kcc,1./60.,false);relocation=out.events.into_iter().find(|e|matches!(e,ActorRuntimeEvent::Relocated{..})).or(relocation);}
    let event=relocation.unwrap();ordinary_enemy_presentation::present_events(&mut s,Some(&scene),&[event.clone()]);let cue=s.presentation_events.last().unwrap();assert_eq!(cue.kind,"SignalBlink");assert_eq!(cue.range_m,Some(1.25));assert_eq!(cue.radius_m,0.3);
    for fault in ["wrong-end","too-far","height","wrong-actor"]{let mut bad=event.clone();if let ActorRuntimeEvent::Relocated{actor_id,from_m,to_m}=&mut bad{match fault{"wrong-end"=>to_m.x_m+=0.1,"too-far"=>from_m.x_m+=2.,"height"=>from_m.y_m=2.,_=>*actor_id="mh_signal_yard_signal_wraith_03".into()}}let before=s.next_presentation_event_id;ordinary_enemy_presentation::present_events(&mut s,Some(&scene),&[bad]);assert_eq!(s.next_presentation_event_id,before,"{fault}");}
}
